### ISSUE TITLE
Test Verification Method Rotation

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#201]
Write unit test for Verification Method Rotation

**Comment by arnabghose997** [comment]
Following is the current approach of Verification Method Rotation:

*Let's assume we have a DID with a verification method `vm1`*

1. Add a new verification method `vm2` to the DID and the associated verification method relationship fields. Sign the DID using the private key associated with `vm1` public key.
2. Remove `vm1` from the verification method list and the associated verification method relationship fields. Sign the DID using the private key associated with `vm2` public key.

There is however another approach, where instead of removing the existing Verification Method, we can instead replace the existing public key with new one, hence the process being done in a single transaction. This would also eliminate the need to remove the verification method ID from VM relationship fields as well. Since, this needs a bit research, this issue will remain open.
